# Python Pandas for Data Analyst

#### 1. What is pandas?
- Pandas is a Python library used for working with data sets.
- It has functions for analyzing, cleaning, exploring, and manipulating data.
- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

#### 2. Why Use Pandas?
- Pandas allows us to analyze big data and make conclusions based on statistical theories.
- Pandas can clean messy data sets, and make them readable and relevant.
- Relevant data is very important in data science.

#### 3. What Can Pandas Do?
- Pandas gives you answers about the data. Like:
- Is there a correlation between two or more columns?
- What is average value?
- Max value?
- Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

# 1. What is a DataFrame?

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:
import pandas as pd

pd.__version__

'3.0.2'

In [ ]:
data = {
    'Name': ["Balkrushna","Soumya","Siddharth","Shivani"],
    'Gender': [ "Male", "Female", "Male", "Female"],
    'Age': [24, 22, 25, 23]
}

# Shift + tab show parameters

In [ ]:
df = pd.DataFrame(data)
print(df)

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25
3     Shivani  Female   23

In [ ]:
print(type(df))

<class 'pandas.DataFrame'>

# 2. Basic Understanding of Dataframes

In [ ]:
df.head(3) # It is used to show top rows (By default it shows 5 rows)

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25

In [ ]:
df.tail(2) # It is used to show bottom rows

        Name  Gender  Age
2  Siddharth    Male   25
3    Shivani  Female   23

In [ ]:
df.shape # It is used to show how many rows and columns in dataframe

(4, 3)

In [ ]:
df.columns # It is used show columns name and its datatype

Index(['Name', 'Gender', 'Age'], dtype='str')

In [ ]:
df.rename(columns = {'Age': 'Person_Age'}, inplace=True ) # Rename is used to change columns name in table and inplace is used to change permanantly

In [ ]:
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [ ]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Gender      4 non-null      str
 2   Person_Age  4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [ ]:
df.describe()  # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

       Person_Age
count    4.000000
mean    23.500000
std      1.290994
min     22.000000
25%     22.750000
50%     23.500000
75%     24.250000
max     25.000000

# 3 Save and Load data from csv

In [ ]:
df.to_csv('Test_data.csv') #Export data frame
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [ ]:
load_df = pd.read_csv('Test_data.csv') # import data
print(load_df)

    Unnamed: 0        Name  Gender  Person_Age
0            0  Balkrushna    Male          24
1            1      Soumya  Female          22
2            2   Siddharth    Male          25
3            3     Shivani  Female          23
4            4   Vaishnavi  Female          24
5            5       Janvi  Female          23
6            6      Ganesh    Male          23
7            7          Om    Male          45
8            8         Adi    Male          22
9            9       Priya  Female          22
10          10         Sai    Male          21

# 4 Rows & Columns - Selection

In [19]:
import pandas as pd 

data = {
    'Name': ['Shreya', 'Priya', 'Jiya', 'Riya', 'Ram', 'Karan'],
    'Age': [22, 23, 20, 18, 19, 24],
    'Gender': ['F', 'F', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
print(df)

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M
5   Karan   24      M

In [ ]:
# Select column

# df[['Name']] # For selecting single column
df[['Name', 'Age']] # For selecting two columns

     Name  Age
0  Shreya   22
1   Priya   23
2    Jiya   20
3    Riya   18
4     Ram   19
5   Karan   24

In [ ]:
# select single row || loc - label based index
df.loc[df.Name=='Priya']

    Name  Age Gender
1  Priya   23      F

In [ ]:
# select multiple rows || loc - label based index

df.loc[0:4]

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M

In [2]:
# Select Rows || iloc - index-value based
df.iloc[0]
# df.iloc[0:2] # [start:stop(less than 1):step]

Name      Shreya
Age           22
Gender         F
Name: 0, dtype: object

# 5. Filter Dataframe - Filtering by column values

In [3]:
df

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M
5   Karan   24      M

In [6]:
df_age_filter = df[df['Age']>=20] #Filter and store dataframe in the new variable
print(df_age_filter)

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
5   Karan   24      M

In [7]:
df[(df['Age']>=20) & (df['Gender']== 'F')]

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F

#### Where(): 
- The where() function in Pandas is used to keep values that satisfy a specified condition and replace values that do not satisfy the condition with another value.

In [9]:


df.where(df['Age']>20, other='less than 20')

           Name           Age        Gender
0        Shreya            22             F
1         Priya            23             F
2  less than 20  less than 20  less than 20
3  less than 20  less than 20  less than 20
4  less than 20  less than 20  less than 20
5         Karan            24             M

# 6 Rows and Columns - Operation (Add, update, delete)

In [21]:
import pandas as pd
data = {
    "Name": ['Soumya','Vaibhav','Himanshu','Pranit','Shivani','Rakesh'],
    "Age": [22,23,24,23,22,25],
    "salary": [22000,45000,67000,100000,150000,50000]

}
df = pd.DataFrame(data)
print(df)

       Name  Age  salary
0    Soumya   22   22000
1   Vaibhav   23   45000
2  Himanshu   24   67000
3    Pranit   23  100000
4   Shivani   22  150000
5    Rakesh   25   50000

In [22]:
# Create a new column
df['Team']= ['Analyst','Developer','Testing','Sales','Cloud','AI']
df

       Name  Age  salary       Team
0    Soumya   22   22000    Analyst
1   Vaibhav   23   45000  Developer
2  Himanshu   24   67000    Testing
3    Pranit   23  100000      Sales
4   Shivani   22  150000      Cloud
5    Rakesh   25   50000         AI

In [25]:
# Add new columns using existing column
df['Bonus'] = df['salary'] * 0.30
df

       Name  Age  salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   50000         AI  15000.0

In [26]:
df.rename(columns= {'salary':'Salary'}, inplace = True)

In [27]:
df

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   50000         AI  15000.0

In [28]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['Janki', 21, 21000, 'IT', 2000]
df

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   50000         AI  15000.0
6     Janki   21   21000         IT   2000.0

In [31]:
# Update value in Dataframe using column value
df.loc[df.Age==25,'Salary']=75000
df

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   75000         AI  15000.0
6     Janki   21   21000         IT   2000.0

In [32]:
df.loc[df.Team == 'IT', 'Salary'] = 80000
df

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   75000         AI  15000.0
6     Janki   21   80000         IT   2000.0

#### Delete value - rows and columns

#### drop():
- The drop() function is used to delete unwanted rows or columns from a Pandas DataFrame based on their labels or indexes. It is commonly used during data cleaning and preprocessing.

In [34]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'Janki'].index)
print(df)

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0
5    Rakesh   25   75000         AI  15000.0

In [35]:
# delete row using index-name filter
df.drop(5, axis=0)

       Name  Age  Salary       Team    Bonus
0    Soumya   22   22000    Analyst   6600.0
1   Vaibhav   23   45000  Developer  13500.0
2  Himanshu   24   67000    Testing  20100.0
3    Pranit   23  100000      Sales  30000.0
4   Shivani   22  150000      Cloud  45000.0

In [41]:
# delete one column
# df.drop('Bonus', axis=1, inplace = True)
# df.drop(['Bonus','Team'],axis = 1) # Delete multiple columns

In [40]:
df

       Name  Age  Salary       Team
0    Soumya   22   22000    Analyst
1   Vaibhav   23   45000  Developer
2  Himanshu   24   67000    Testing
3    Pranit   23  100000      Sales
4   Shivani   22  150000      Cloud
5    Rakesh   25   75000         AI

#### sort_values(): 
- The sort_values() function is used to arrange DataFrame rows based on the values of one or more columns in ascending or descending order. It helps organize and analyze data more effectively.

In [42]:
df.sort_values('Salary') # Ascending order, by default

       Name  Age  Salary       Team
0    Soumya   22   22000    Analyst
1   Vaibhav   23   45000  Developer
2  Himanshu   24   67000    Testing
5    Rakesh   25   75000         AI
3    Pranit   23  100000      Sales
4   Shivani   22  150000      Cloud

In [44]:
df.sort_values(['Age','Salary'],ascending = False)

       Name  Age  Salary       Team
5    Rakesh   25   75000         AI
2  Himanshu   24   67000    Testing
3    Pranit   23  100000      Sales
1   Vaibhav   23   45000  Developer
4   Shivani   22  150000      Cloud
0    Soumya   22   22000    Analyst

# 7. Working with Date Value: