# Python Pandas for Data Science

1. What is pandas?
-Pandas is a Python library used for working with data sets.
-It has functions for analyzing, cleaning, exploring, and manipulating data.
-The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

2. Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.
Pandas can clean messy data sets, and make them readable and relevant.
Relevant data is very important in data science.

3. What Can Pandas Do?
Pandas gives you answers about the data. Like:
Is there a correlation between two or more columns?
What is average value?
Max value?
Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

# 1. What is a DataFrame?

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [2]:
import pandas as pd

pd.__version__

'3.0.2'

In [ ]:
data = {
    'Name': ["Balkrushna","Soumya","Siddharth","Shivani"],
    'Gender': [ "Male", "Female", "Male", "Female"],
    'Age': [24, 22, 25, 23]
}

# Shift + tab show parameters

In [7]:
df = pd.DataFrame(data)
print(df)

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25
3     Shivani  Female   23

In [9]:
print(type(df))

<class 'pandas.DataFrame'>

# 2. Basic Understanding of Dataframes

In [12]:
df.head(3) # It is used to show top rows

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25

In [14]:
df.tail(2) # It is used to show bottom rows

        Name  Gender  Age
2  Siddharth    Male   25
3    Shivani  Female   23

In [19]:
df.shape # It is used to show how many rows and columns in dataframe

(4, 3)

In [18]:
df.columns # It is used show columns name and its datatype

Index(['Name', 'Gender', 'Age'], dtype='str')

In [27]:
df.rename(columns = {'Age': 'Person_Age'}, inplace=True ) # Rename is used to change columns name in table and inplace is used to change permanantly

In [28]:
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [29]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Gender      4 non-null      str
 2   Person_Age  4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [32]:
df.describe()  # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

       Person_Age
count    4.000000
mean    23.500000
std      1.290994
min     22.000000
25%     22.750000
50%     23.500000
75%     24.250000
max     25.000000

# 3 Save and Load data from csv

In [35]:
df.to_csv('Test_data.csv') #Export data frame
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [38]:
load_df = pd.read_csv('Test_data.csv') # import data
print(load_df)

    Unnamed: 0        Name  Gender  Person_Age
0            0  Balkrushna    Male          24
1            1      Soumya  Female          22
2            2   Siddharth    Male          25
3            3     Shivani  Female          23
4            4   Vaishnavi  Female          24
5            5       Janvi  Female          23
6            6      Ganesh    Male          23
7            7          Om    Male          45
8            8         Adi    Male          22
9            9       Priya  Female          22
10          10         Sai    Male          21

# 4 Rows & Columns - Selection