# Python Pandas for Data Analyst

#### 1. What is pandas?
- Pandas is a Python library used for working with data sets.
- It has functions for analyzing, cleaning, exploring, and manipulating data.
- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

#### 2. Why Use Pandas?
- Pandas allows us to analyze big data and make conclusions based on statistical theories.
- Pandas can clean messy data sets, and make them readable and relevant.
- Relevant data is very important in data science.

#### 3. What Can Pandas Do?
- Pandas gives you answers about the data. Like:
- Is there a correlation between two or more columns?
- What is average value?
- Max value?
- Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

# 1. What is a DataFrame?

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:
import pandas as pd

pd.__version__

'3.0.2'

In [ ]:
data = {
    'Name': ["Balkrushna","Soumya","Siddharth","Shivani"],
    'Gender': [ "Male", "Female", "Male", "Female"],
    'Age': [24, 22, 25, 23]
}

# Shift + tab show parameters

In [ ]:
df = pd.DataFrame(data)
print(df)

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25
3     Shivani  Female   23

In [ ]:
print(type(df))

<class 'pandas.DataFrame'>

# 2. Basic Understanding of Dataframes

In [ ]:
df.head(3) # It is used to show top rows (By default it shows 5 rows)

         Name  Gender  Age
0  Balkrushna    Male   24
1      Soumya  Female   22
2   Siddharth    Male   25

In [ ]:
df.tail(2) # It is used to show bottom rows

        Name  Gender  Age
2  Siddharth    Male   25
3    Shivani  Female   23

In [ ]:
df.shape # It is used to show how many rows and columns in dataframe

(4, 3)

In [ ]:
df.columns # It is used show columns name and its datatype

Index(['Name', 'Gender', 'Age'], dtype='str')

In [ ]:
df.rename(columns = {'Age': 'Person_Age'}, inplace=True ) # Rename is used to change columns name in table and inplace is used to change permanantly

In [ ]:
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [ ]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Gender      4 non-null      str
 2   Person_Age  4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [ ]:
df.describe()  # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

       Person_Age
count    4.000000
mean    23.500000
std      1.290994
min     22.000000
25%     22.750000
50%     23.500000
75%     24.250000
max     25.000000

# 3 Save and Load data from csv

In [ ]:
df.to_csv('Test_data.csv') #Export data frame
df

         Name  Gender  Person_Age
0  Balkrushna    Male          24
1      Soumya  Female          22
2   Siddharth    Male          25
3     Shivani  Female          23

In [ ]:
load_df = pd.read_csv('Test_data.csv') # import data
print(load_df)

    Unnamed: 0        Name  Gender  Person_Age
0            0  Balkrushna    Male          24
1            1      Soumya  Female          22
2            2   Siddharth    Male          25
3            3     Shivani  Female          23
4            4   Vaishnavi  Female          24
5            5       Janvi  Female          23
6            6      Ganesh    Male          23
7            7          Om    Male          45
8            8         Adi    Male          22
9            9       Priya  Female          22
10          10         Sai    Male          21

# 4 Rows & Columns - Selection

In [ ]:
import pandas as pd 

data = {
    'Name': ['Shreya', 'Priya', 'Jiya', 'Riya', 'Ram', 'Karan'],
    'Age': [22, 23, 20, 18, 19, 24],
    'Gender': ['F', 'F', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
print(df)

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M
5   Karan   24      M

In [ ]:
# Select column

# df[['Name']] # For selecting single column
df[['Name', 'Age']] # For selecting two columns

     Name  Age
0  Shreya   22
1   Priya   23
2    Jiya   20
3    Riya   18
4     Ram   19
5   Karan   24

In [ ]:
# select single row || loc - label based index
df.loc[df.Name=='Priya']

    Name  Age Gender
1  Priya   23      F

In [ ]:
# select multiple rows || loc - label based index

df.loc[0:4]

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M

In [ ]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop(less than 1):step]

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F

# 5. Pandas Read CSV

- A simple way to store big data sets is to use CSV files (comma separated files).
- CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

In [ ]:
df = pd.read_csv('students_data.csv')
#  print(df.to_string())
print(df.head(5))
# print(df.tail(5))


# to_string() used to print entire dataframe
#If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows:

#Check the number of maximum returned rows:

#  print(pd.options.display.max_rows)

   student_id              name  age  gender  department  semester  marks  \
0           1      Cheryl Henry   23  Female        ENTC         3     59
1           2    Joseph Cobb MD   24    Male        ENTC         7     39
2           3       Diane Ayala   23  Female  Mechanical         2     91
3           4  Kenneth Mitchell   20    Male    Computer         8     85
4           5        Joseph Cox   20  Female        ENTC         3     58

   attendance_percentage      city
0                     80      Pune
1                     77  Kolhapur
2                     99  Kolhapur
3                     81      Pune
4                     86      Pune

# 6. Read JSON

- Big data sets are often stored, or extracted as JSON.
- JSON is plain text, but has the format of an object, and is well known in the world of programming, including Pandas.

In [ ]:
df = pd.read_json('employees_dataset.json')
print(df.to_string())

    employee_id         name  age department  salary  experience_years       city
0             1   Employee_1   44    Finance   97011                13  Bangalore
1             2   Employee_2   37    Finance   88775                19       Pune
2             3   Employee_3   36    Finance   73647                 7  Bangalore
3             4   Employee_4   40    Finance   46955                20  Bangalore
4             5   Employee_5   33    Finance   81118                20      Delhi
5             6   Employee_6   39         IT   66168                 7     Mumbai
6             7   Employee_7   23  Marketing   68294                 8  Bangalore
7             8   Employee_8   31         HR   83354                20       Pune
8             9   Employee_9   33    Finance   95117                 6     Mumbai
9            10  Employee_10   31  Marketing   30104                 4       Pune
10           11  Employee_11   25         HR   77734                 7      Delhi
11           12  Employee_12   26      Sales   57988                11  Bangalore
12           13  Employee_13   41         HR   26349                19      Delhi
13           14  Employee_14   29    Finance   65149                12     Mumbai
14           15  Employee_15   24         IT   38857                11     Mumbai
15           16  Employee_16   41         IT   42928                11      Delhi
16           17  Employee_17   28  Marketing   33434                 1       Pune
17           18  Employee_18   30      Sales   88737                 7  Bangalore
18           19  Employee_19   33  Marketing   37479                13      Delhi
19           20  Employee_20   39    Finance   84257                10  Bangalore
20           21  Employee_21   29      Sales   50980                 2  Bangalore
21           22  Employee_22   33    Finance   54003                 8  Bangalore
22           23  Employee_23   23      Sales   26395                 5  Bangalore
23           24  Employee_24   34    Finance   33050                 1  Bangalore
24           25  Employee_25   29  Marketing   96855                 5  Bangalore
25           26  Employee_26   28      Sales   83509                 7      Delhi
26           27  Employee_27   34    Finance   78057                 8      Delhi
27           28  Employee_28   35  Marketing   35062                10       Pune
28           29  Employee_29   32         HR   84133                 2       Pune
29           30  Employee_30   44         IT   68468                 7     Mumbai
30           31  Employee_31   27         IT   27757                20       Pune
31           32  Employee_32   29    Finance   94474                 7       Pune
32           33  Employee_33   40    Finance   83849                16     Mumbai
33           34  Employee_34   35  Marketing   75688                14     Mumbai
34           35  Employee_35   43    Finance   88587                 9     Mumbai
35           36  Employee_36   33         HR   35904                20  Bangalore
36           37  Employee_37   39         HR   69723                15  Bangalore
37           38  Employee_38   32         HR   91398                17      Delhi
38           39  Employee_39   34    Finance   40619                 7     Mumbai
39           40  Employee_40   23      Sales   45821                11  Bangalore
40           41  Employee_41   35    Finance   80173                14      Delhi
41           42  Employee_42   30         IT   52348                 5     Mumbai
42           43  Employee_43   29      Sales   94692                 6  Bangalore
43           44  Employee_44   43      Sales   53676                 2  Bangalore
44           45  Employee_45   42         IT   77086                13  Bangalore
45           46  Employee_46   38         IT   28841                 4     Mumbai
46           47  Employee_47   44         HR   34421                12     Mumbai
47           48  Employee_48   39         IT   80033                13       Pune
48           49  Employee_49   45         HR   66291                 1  Bangalore
49           50  Employee_50   30      Sales   89845                 1      Delhi

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       50 non-null     int64
 1   name              50 non-null     str
 2   age               50 non-null     int64
 3   department        50 non-null     str
 4   salary            50 non-null     int64
 5   experience_years  50 non-null     int64
 6   city              50 non-null     str
dtypes: int64(4), str(3)
memory usage: 2.9 KB

In [ ]:
df.describe()

       employee_id        age        salary  experience_years
count     50.00000  50.000000     50.000000         50.000000
mean      25.50000  33.880000  64103.860000          9.760000
std       14.57738   6.196246  23177.204411          5.766051
min        1.00000  23.000000  26349.000000          1.000000
25%       13.25000  29.000000  41196.250000          6.000000
50%       25.50000  33.000000  68381.000000          8.500000
75%       37.75000  39.000000  83764.000000         13.000000
max       50.00000  45.000000  97011.000000         20.000000

# 7. Pandas - Cleaning Data

- Data cleaning means fixing bad data in your data set.
- Bad data could be:

Empty cells,
Data in wrong format,
Wrong data,
Duplicates etc.

#### 7.1 Pandas - Cleaning Empty Cells

- Empty cells can potentially give you a wrong result when you analyze data.

In [ ]:
df1 = pd.read_csv('data_set.csv')
print(df1.to_string())

    id    name     age   salary  joining_date department
0    1   Rahul      21  25000.0    2024-01-15         IT
1    2   Priya      22  30000.0    15/02/2024         HR
2    3     NaN      23      NaN    2024/03/10    Finance
3    4    Amit     NaN  45000.0  April 5 2024         IT
4    5   Sneha  Twenty  50000.0    2024-13-01        NaN
5    5   Sneha      24  50000.0           NaN         IT
6    7   Vikas      25  -1000.0    2024-06-20      Sales
7    8     NaN      26  70000.0    20-07-2024         HR
8    9   Pooja     NaN  80000.0    2024-08-25    Finance
9   10   Karan      28      NaN    09/15/2024         IT
10  11  Anjali      29  55000.0           NaN        NaN
11  12   Rohit      30  62000.0    2024-11-11  Marketing

In [ ]:
new_df = df1.dropna()
print(new_df.to_string())

# By default, the dropna() method returns a new DataFrame, and will not change the original.
# If you want to change the original DataFrame, use the inplace = True argument:

    id   name age   salary joining_date department
0    1  Rahul  21  25000.0   2024-01-15         IT
1    2  Priya  22  30000.0   15/02/2024         HR
6    7  Vikas  25  -1000.0   2024-06-20      Sales
11  12  Rohit  30  62000.0   2024-11-11  Marketing

Note: Now, the dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

##### Replace Empty Values

- Another way of dealing with empty cells is to insert a new value instead.
- This way you do not have to delete entire rows just because of some empty cells.
- The fillna() method allows us to replace empty cells with a value:

In [ ]:
print(df1.isnull().sum())

id              0
name            0
age             0
salary          2
joining_date    2
department      2
dtype: int64

In [ ]:
df = pd.read_csv('data_set.csv')
print(df.to_string())

    id    name     age   salary  joining_date department
0    1   Rahul      21  25000.0    2024-01-15         IT
1    2   Priya      22  30000.0    15/02/2024         HR
2    3     NaN      23      NaN    2024/03/10    Finance
3    4    Amit     NaN  45000.0  April 5 2024         IT
4    5   Sneha  Twenty  50000.0    2024-13-01        NaN
5    5   Sneha      24  50000.0           NaN         IT
6    7   Vikas      25  -1000.0    2024-06-20      Sales
7    8     NaN      26  70000.0    20-07-2024         HR
8    9   Pooja     NaN  80000.0    2024-08-25    Finance
9   10   Karan      28      NaN    09/15/2024         IT
10  11  Anjali      29  55000.0           NaN        NaN
11  12   Rohit      30  62000.0    2024-11-11  Marketing

In [ ]:
# Display missing values
print(df.isnull().sum())

# Fill missing values

# Fill missing names with "Unknown"
df["name"] = df["name"].fillna("Unknown")

# Fill missing age with average age
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["age"] = df["age"].fillna(df["age"].mean())

# Fill missing salary with average salary
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df["salary"] = df["salary"].fillna(df["salary"].mean())

# Fill missing joining_date with "Not Available"
df["joining_date"] = df["joining_date"].fillna("Not Available")

# Fill missing department with "General"
df["department"] = df["department"].fillna("General")

# Display updated dataset
print(df)

id              0
name            2
age             2
salary          2
joining_date    2
department      2
dtype: int64
    id     name        age   salary   joining_date department
0    1    Rahul  21.000000  25000.0     2024-01-15         IT
1    2    Priya  22.000000  30000.0     15/02/2024         HR
2    3  Unknown  23.000000  46600.0     2024/03/10    Finance
3    4     Amit  25.333333  45000.0   April 5 2024         IT
4    5    Sneha  25.333333  50000.0     2024-13-01    General
5    5    Sneha  24.000000  50000.0  Not Available         IT
6    7    Vikas  25.000000  -1000.0     2024-06-20      Sales
7    8  Unknown  26.000000  70000.0     20-07-2024         HR
8    9    Pooja  25.333333  80000.0     2024-08-25    Finance
9   10    Karan  28.000000  46600.0     09/15/2024         IT
10  11   Anjali  29.000000  55000.0  Not Available    General
11  12    Rohit  30.000000  62000.0     2024-11-11  Marketing

# Resume - Pandas

#### Filter Dataframe

In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.2'

In [3]:
data = {
    'Name': ['Shreya', 'Priya', 'Jiya', 'Riya', 'Ram', 'Karan'],
    'Age': [22, 23, 20, 18, 19, 24],
    'Gender': ['F', 'F', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
print(df)

     Name  Age Gender
0  Shreya   22      F
1   Priya   23      F
2    Jiya   20      F
3    Riya   18      F
4     Ram   19      M
5   Karan   24      M

In [5]:
df_age_filter = df[df['Age']>=23]
print(df_age_filter)

    Name  Age Gender
1  Priya   23      F
5  Karan   24      M

In [7]:
df.where(df['Age']>=23,other = 'Not Eligible')

           Name           Age        Gender
0  Not Eligible  Not Eligible  Not Eligible
1         Priya            23             F
2  Not Eligible  Not Eligible  Not Eligible
3  Not Eligible  Not Eligible  Not Eligible
4  Not Eligible  Not Eligible  Not Eligible
5         Karan            24             M