# Pandas Leetcode Problems: 

## What is Pandas?
- Pandas is a popular open-source Python library used for data analysis and manipulation. It provides powerful tools for working with structured data such as tables, spreadsheets, and CSV files.
## The two main pandas data structures are:
1. Series – a one-dimensional labeled array.
2. DataFrame – a two-dimensional table with rows and columns (similar to a spreadsheet).

In [2]:
# import pandas
import pandas as pd
pd.__version__

'3.0.2'

Write a solution to find the IDs of the invalid tweets. The tweet is invalid if the number of characters used in the content of the tweet is strictly greater than 15.

Return the result table in any order.

The result format is in the following example.

In [1]:
import pandas as pd

# Create Tweets table
tweets = pd.DataFrame({
    "tweet_id": [1, 2],
    "content": [
        "Let us Code",
        "More than fifteen chars are here!"
    ]
})

print(tweets)

   tweet_id                            content
0         1                        Let us Code
1         2  More than fifteen chars are here!

In [3]:
tweets[tweets['content'].str.len() > 15][['tweet_id']]

   tweet_id
1         2

# 2
Write a solution to calculate the bonus of each employee. The bonus of an employee is 100% of their salary if the ID of the employee is an odd number and the employee's name does not start with the character 'M'. The bonus of an employee is 0 otherwise.

Return the result table ordered by employee_id.

The result format is in the following example.

In [1]:
import pandas as pd 

data = {
    'employee_id': [2,3,7,8,9],
    'name': ['Meir','Michael', 'Addilyn','Juan','kannon'],
    'salary': [3000,3800,7400,6100,7700]
}

In [2]:
df = pd.DataFrame(data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   employee_id     name  salary
0            2     Meir    3000
1            3  Michael    3800
2            7  Addilyn    7400
3            8     Juan    6100
4            9   kannon    7700

In [4]:
df[df['name'].str.startswith('M')]

   employee_id     name  salary
0            2     Meir    3000
1            3  Michael    3800